// ============================================================
// ROTA DO CAFÉ DO SUL DE MINAS — Base de Dados
// Municípios: Varginha • Três Pontas • Cambuquira
// ============================================================

const EXPERIENCIAS = [

  // ── VARGINHA ─────────────────────────────────────────────

  {
    id: 1,
    slug: 'cupping-varginha',
    titulo: 'Cupping Experience — Capital Mundial do Café',
    subtitulo: 'Desperte seus sentidos na cidade mais famosa do café no Brasil',
    categoria: 'fazenda',
    municipio: 'Varginha',
    preco: 120,
    duracao: '3 horas',
    duracaoMin: 3,
    disponibilidade: ['Ter','Qua','Qui','Sex','Sáb'],
    horarios: ['09:00','14:00'],
    minimoPersonas: 2,
    maximoPersonas: 16,
    comGuia: true,
    transporteIncluso: false,
    transporteInfo: 'Centro de Varginha, fácil acesso a pé do hotel.',
    nivel: 'Fácil',
    rating: 4.9,
    totalAvaliacoes: 142,
    destaque: true,
    gratuita: false,
    imagem: 'assets/images/cupping.jpg',
    galeria: ['assets/images/cupping.jpg','assets/images/cafe-beans.jpg'],
    tags: ['cupping','degustação','barista','café especial','Varginha'],
    descricao: 'Varginha é reconhecida mundialmente como a Capital do Café. Nesta sessão de cupping conduzida por um barista campeão, você vai aprender a identificar notas aromáticas, acidez, corpo e complexidade dos melhores cafés produzidos no Sul de Minas. Uma experiência sensorial única que transforma para sempre sua relação com o café.',
    incluso: ['Sessão de cupping com 6 amostras de café especial','Barista certificado pela SCAA como guia','Material didático ilustrado','Café especial para levar (50g)'],
    naoIncluso: ['Transporte','Refeições'],
    oQueLevar: ['Vontade de descobrir novos sabores'],
    itinerario: [
      {hora:'09:00', atividade:'Boas-vindas e história do café em Varginha'},
      {hora:'09:20', atividade:'Técnica do cupping: explicação e demonstração'},
      {hora:'09:45', atividade:'Degustação das 6 amostras — notas e avaliação individual'},
      {hora:'11:00', atividade:'Comparativo: café especial x café comercial'},
      {hora:'11:30', atividade:'Sessão de perguntas e loja de produtos'},
      {hora:'12:00', atividade:'Encerramento'}
    ],
    cancelamento: 'Cancelamento gratuito até 24h antes.',
    anfitriao: {
      nome: 'Rafael Cunha — Barista Campeão',
      bio: 'Barista certificado pela SCAA com 12 anos de experiência. Já treinou equipes em toda a América do Sul. Radicado em Varginha.',
      foto: 'assets/images/cupping.jpg'
    }
  },

  {
    id: 2,
    slug: 'jantar-harmonizado-varginha',
    titulo: 'Jantar Harmonizado: Café & Culinária Mineira',
    subtitulo: 'Uma experiência gastronômica sofisticada e inédita',
    categoria: 'gastronomia',
    municipio: 'Varginha',
    preco: 280,
    duracao: '3 horas',
    duracaoMin: 3,
    disponibilidade: ['Sex','Sáb'],
    horarios: ['19:30'],
    minimoPersonas: 2,
    maximoPersonas: 16,
    comGuia: true,
    transporteIncluso: false,
    transporteInfo: 'Restaurante no centro de Varginha.',
    nivel: 'Fácil',
    rating: 4.8,
    totalAvaliacoes: 52,
    destaque: true,
    gratuita: false,
    imagem: 'assets/images/jantar-harmonizado.jpg',
    galeria: ['assets/images/jantar-harmonizado.jpg','assets/images/gastronomia.jpg'],
    tags: ['jantar','harmonização','café','gourmet','Varginha'],
    descricao: 'Menu de 5 tempos criado pelo chef Alexandre Souza, onde cada prato é harmonizado com um café especial diferente produzido no Sul de Minas. Uma experiência que quebra todos os preconceitos sobre o café e revela sua versatilidade: do aperitivo ao digestivo.',
    incluso: ['Menu degustação de 5 tempos','Harmonização com 5 cafés especiais','Apresentação do chef e barista','Receitas do menu'],
    naoIncluso: ['Bebidas além da harmonização','Transfer'],
    oQueLevar: ['Traje a rigor casual'],
    itinerario: [
      {hora:'19:30', atividade:'Recepção: espuma de café com petiscos'},
      {hora:'20:00', atividade:'1° tempo: Entrada fria + café natural'},
      {hora:'20:30', atividade:'2° tempo: Risoto de queijo + café honey'},
      {hora:'21:00', atividade:'3° tempo: Prato principal + café washed'},
      {hora:'21:30', atividade:'Sobremesa: brigadeiro gourmet + espresso'},
      {hora:'22:00', atividade:'Digestivo com café envelhecido'}
    ],
    cancelamento: 'Cancelamento gratuito até 72h antes.',
    anfitriao: {
      nome: 'Chef Alexandre Souza',
      bio: 'Chef com 15 anos de experiência em culinária regional mineira com técnicas contemporâneas.',
      foto: 'assets/images/jantar-harmonizado.jpg'
    }
  },

  {
    id: 3,
    slug: 'rota-mercados-varginha',
    titulo: 'Rota dos Mercados e Sabores de Varginha',
    subtitulo: 'Gastronomia e cultura cafeeira na Capital Mundial do Café',
    categoria: 'cultural',
    municipio: 'Varginha',
    preco: 70,
    duracao: '3 horas',
    duracaoMin: 3,
    disponibilidade: ['Sáb'],
    horarios: ['09:00'],
    minimoPersonas: 4,
    maximoPersonas: 20,
    comGuia: true,
    transporteIncluso: false,
    transporteInfo: 'Saída da praça principal de Varginha.',
    nivel: 'Fácil',
    rating: 4.6,
    totalAvaliacoes: 78,
    destaque: false,
    gratuita: false,
    imagem: 'assets/images/mercado-varginha.jpg',
    galeria: ['assets/images/mercado-varginha.jpg','assets/images/gastronomia.jpg'],
    tags: ['mercado','gastronômico','city tour','Varginha'],
    descricao: 'Tour pelos melhores pontos gastronômicos e cafeeiros de Varginha: Mercado Municipal, cafeterias independentes, torrefação histórica e o famoso monumento do ET de Varginha. Um mix de cultura, gastronomia e história local.',
    incluso: ['Guia local especializado','Degustação em 3 estabelecimentos','Ingresso a 1 torrefação histórica'],
    naoIncluso: ['Compras nos mercados','Refeições'],
    oQueLevar: ['Calçado confortável para caminhada'],
    itinerario: [
      {hora:'09:00', atividade:'Encontro na praça e história de Varginha'},
      {hora:'09:30', atividade:'Mercado Municipal — produtores locais'},
      {hora:'10:30', atividade:'Visita à torrefação histórica'},
      {hora:'11:00', atividade:'Tour pelas cafeterias independentes'},
      {hora:'12:00', atividade:'Encerramento com café e quitutes'}
    ],
    cancelamento: 'Cancelamento gratuito até 24h antes.',
    anfitriao: {
      nome: 'Guias de Varginha',
      bio: 'Guias locais credenciados pela Secretaria de Turismo de Varginha. Especialistas na história cafeeira da região.',
      foto: 'assets/images/mercado-varginha.jpg'
    }
  },

  {
    id: 4,
    slug: 'rota-cafeterias-varginha',
    titulo: 'Rota de Cafeterias Independentes',
    subtitulo: 'As melhores cafeterias especializadas de Varginha — guia autoguiado',
    categoria: 'gratuita',
    municipio: 'Varginha',
    preco: 0,
    duracao: '2 horas',
    duracaoMin: 2,
    disponibilidade: ['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
    horarios: ['Livre — horário das cafeterias'],
    minimoPersonas: 1,
    maximoPersonas: 999,
    comGuia: false,
    transporteIncluso: false,
    transporteInfo: 'Centro de Varginha — todas as cafeterias a pé.',
    nivel: 'Fácil',
    rating: 4.7,
    totalAvaliacoes: 224,
    destaque: false,
    gratuita: true,
    imagem: 'assets/images/cafeteria-especial.jpg',
    galeria: ['assets/images/cafeteria-especial.jpg'],
    tags: ['gratuita','cafeterias','Varginha','café especial','autoguiada'],
    descricao: 'Mapa autoguiado digital com as melhores cafeterias independentes do centro de Varginha. Cada casa tem sua própria identidade, seleção de cafés especiais e microlotes da temporada. O mapa inclui avaliação dos baristas locais e dicas exclusivas.',
    incluso: ['Mapa digital das cafeterias (gratuito)','Dicas dos baristas locais','Acesso às cafeterias'],
    naoIncluso: ['Consumo nas cafeterias (por conta do visitante)'],
    oQueLevar: ['Câmera','Apetite por café'],
    itinerario: [
      {hora:'Livre', atividade:'Cafeteria 1 — Coado Filtrado: café natural de Varginha'},
      {hora:'+40min', atividade:'Cafeteria 2 — Espresso Bar: blend premiado da safra'},
      {hora:'+80min', atividade:'Cafeteria 3 — Origem: microlote exclusivo'},
      {hora:'+120min', atividade:'Cafeteria 4 — Manifesto: café da comunidade'}
    ],
    cancelamento: 'Experiência livre — sem necessidade de reserva.',
    anfitriao: {
      nome: 'Associação de Cafeterias de Varginha',
      bio: 'Iniciativa coletiva de empreendedores locais que conectam o turista ao universo dos cafés especiais.',
      foto: 'assets/images/cafeteria-especial.jpg'
    }
  },

  {
    id: 5,
    slug: 'torra-assistida-varginha',
    titulo: 'Torra Artesanal Assistida',
    subtitulo: 'Opere um torrador e crie seu próprio café na Capital do Café',
    categoria: 'fazenda',
    municipio: 'Varginha',
    preco: 160,
    duracao: '3h30',
    duracaoMin: 3.5,
    disponibilidade: ['Sáb','Dom'],
    horarios: ['09:00'],
    minimoPersonas: 2,
    maximoPersonas: 8,
    comGuia: true,
    transporteIncluso: false,
    transporteInfo: 'Torrefação no centro de Varginha.',
    nivel: 'Fácil',
    rating: 4.8,
    totalAvaliacoes: 61,
    destaque: false,
    gratuita: false,
    imagem: 'assets/images/torra-artesanal.jpg',
    galeria: ['assets/images/torra-artesanal.jpg','assets/images/cafe-beans.jpg'],
    tags: ['torra','café','artesanal','degustação','Varginha'],
    descricao: 'Você vai operar um torrador artesanal e acompanhar em tempo real todas as fases da torra — do verde ao 1° crack, passando pelo desenvolvimento até o ponto ideal. O mestre torrador explica cada detalhe e ao final você degusta e leva o café que você mesmo criou.',
    incluso: ['Torra assistida com mestre torrador','Degustação do café preparado','Café para levar (100g da sua torra)','Lanche típico mineiro'],
    naoIncluso: ['Transporte'],
    oQueLevar: ['Curiosidade e paladar aventureiro'],
    itinerario: [
      {hora:'09:00', atividade:'Apresentação dos grãos verdes e origens'},
      {hora:'09:30', atividade:'Operação do torrador artesanal — mãos na massa'},
      {hora:'10:30', atividade:'Moagem e preparação do café torrado'},
      {hora:'11:00', atividade:'Degustação comparada — sua torra vs referência'},
      {hora:'12:00', atividade:'Embalagem e encerramento'}
    ],
    cancelamento: 'Cancelamento gratuito até 48h antes.',
    anfitriao: {
      nome: 'Torrefação Mestres do Café — Varginha',
      bio: 'Torrefação especializada em cafés especiais com 20 anos de tradição em Varginha. Referência nacional.',
      foto: 'assets/images/torra-artesanal.jpg'
    }
  },

  // ── TRÊS PONTAS ───────────────────────────────────────────

  {
    id: 6,
    slug: 'pe-a-xicara-tres-pontas',
    titulo: 'Do Pé à Xícara — Fazenda Serra Azul',
    subtitulo: 'Conheça toda a cadeia produtiva do café premiado de Três Pontas',
    categoria: 'fazenda',
    municipio: 'Três Pontas',
    preco: 200,
    duracao: '6 horas',
    duracaoMin: 6,
    disponibilidade: ['Sáb','Dom'],
    horarios: ['08:00'],
    minimoPersonas: 2,
    maximoPersonas: 10,
    comGuia: true,
    transporteIncluso: true,
    transporteInfo: 'Transfer incluso saindo da praça central de Três Pontas.',
    nivel: 'Moderado',
    rating: 5.0,
    totalAvaliacoes: 44,
    destaque: true,
    gratuita: false,
    imagem: 'assets/images/cafezal-fazenda.jpg',
    galeria: ['assets/images/cafezal-fazenda.jpg','assets/images/cupping.jpg','assets/images/cafe-beans.jpg'],
    tags: ['imersão','café especial','fazenda','almoço','Três Pontas'],
    descricao: 'A experiência mais completa do município. Em 6 horas você vai conhecer toda a cadeia produtiva do café na Fazenda Serra Azul — plantio, florada, colheita seletiva, processamento, secagem, torra e preparo. Inclui almoço típico mineiro no fogão a lenha com vista para os cafezais e um cupping final com barista certificado.',
    incluso: ['Tour completo pela cadeia produtiva','Guia agrônomo especializado','Almoço típico mineiro (fogão a lenha)','Cupping final com barista','Transfer saindo do centro','Café especial para levar (200g)'],
    naoIncluso: ['Bebidas alcoólicas','Passeios extras'],
    oQueLevar: ['Roupas confortáveis e calçado fechado','Repelente','Câmera fotográfica'],
    itinerario: [
      {hora:'08:00', atividade:'Transfer da praça central de Três Pontas'},
      {hora:'08:30', atividade:'Chegada e café da manhã mineiro na fazenda'},
      {hora:'09:00', atividade:'Tour pelo cafezal — crescimento, florada e frutificação'},
      {hora:'10:00', atividade:'Colheita seletiva manual — mãos na massa'},
      {hora:'11:00', atividade:'Processamento: lavagem, boia e secagem'},
      {hora:'12:00', atividade:'Almoço típico mineiro na varanda da sede'},
      {hora:'13:30', atividade:'Torra artesanal e classificação dos grãos'},
      {hora:'14:30', atividade:'Cupping final — prove o café da fazenda'},
      {hora:'15:30', atividade:'Transfer de volta ao centro'}
    ],
    cancelamento: 'Cancelamento gratuito até 72h antes.',
    anfitriao: {
      nome: 'Fazenda Serra Azul — Família Costa',
      bio: 'Produtores de café especial classificado entre os melhores de Minas Gerais. Certificados pela BSCA com pontuação acima de 85 pontos.',
      foto: 'assets/images/cafezal-fazenda.jpg'
    }
  },

  {
    id: 7,
    slug: 'torra-assistida-tres-pontas',
    titulo: 'Torra Assistida e Degustação',
    subtitulo: 'Acompanhe a transformação do grão verde ao café perfeito',
    categoria: 'fazenda',
    municipio: 'Três Pontas',
    preco: 150,
    duracao: '3h30',
    duracaoMin: 3.5,
    disponibilidade: ['Sáb','Dom'],
    horarios: ['09:00'],
    minimoPersonas: 2,
    maximoPersonas: 8,
    comGuia: true,
    transporteIncluso: false,
    transporteInfo: 'Torrefação localizada no centro de Três Pontas.',
    nivel: 'Fácil',
    rating: 4.7,
    totalAvaliacoes: 67,
    destaque: false,
    gratuita: false,
    imagem: 'assets/images/degustacao-cafe.jpg',
    galeria: ['assets/images/degustacao-cafe.jpg','assets/images/cafe-beans.jpg'],
    tags: ['torra','café','artesanal','Três Pontas'],
    descricao: 'Você vai operar um torrador artesanal e acompanhar em tempo real todas as fases da torra. O mestre torrador de Três Pontas — município reconhecido pela qualidade dos seus cafés — explica cada detalhe e ao final você leva o café que torrou.',
    incluso: ['Torra assistida com mestre torrador','Degustação','Café para levar (100g)','Lanche típico'],
    naoIncluso: ['Transporte'],
    oQueLevar: ['Curiosidade e paladar aventureiro'],
    itinerario: [
      {hora:'09:00', atividade:'Apresentação dos grãos verdes de Três Pontas'},
      {hora:'09:30', atividade:'Operação do torrador artesanal'},
      {hora:'10:30', atividade:'Moagem e preparação'},
      {hora:'11:00', atividade:'Degustação comparada'},
      {hora:'12:00', atividade:'Embalagem e encerramento'}
    ],
    cancelamento: 'Cancelamento gratuito até 48h antes.',
    anfitriao: {
      nome: 'Torrefação Mantiqueira — Três Pontas',
      bio: 'Família com 3 gerações de experiência em torra artesanal em Três Pontas.',
      foto: 'assets/images/degustacao-cafe.jpg'
    }
  },

  {
    id: 8,
    slug: 'almoco-fazenda-tres-pontas',
    titulo: 'Almoço na Fazenda com Vista para o Cafezal',
    subtitulo: 'Mesa farta de culinária mineira em plena natureza',
    categoria: 'gastronomia',
    municipio: 'Três Pontas',
    preco: 130,
    duracao: '3 horas',
    duracaoMin: 3,
    disponibilidade: ['Sáb','Dom'],
    horarios: ['12:00'],
    minimoPersonas: 4,
    maximoPersonas: 25,
    comGuia: false,
    transporteIncluso: false,
    transporteInfo: 'Fazenda a 12km do centro. Transfer disponível por +R$ 35/pax.',
    nivel: 'Fácil',
    rating: 4.8,
    totalAvaliacoes: 88,
    destaque: true,
    gratuita: false,
    imagem: 'assets/images/almoco-fazenda.jpg',
    galeria: ['assets/images/almoco-fazenda.jpg'],
    tags: ['gastronomia','almoço','fazenda','culinária mineira','Três Pontas'],
    descricao: 'Uma experiência gastronômica autêntica em uma fazenda de café de Três Pontas. O almoço é preparado no fogão a lenha com receitas passadas de geração em geração: frango ao molho pardo, feijão tropeiro, angu com queijo, couve refogada e doce de leite caseiro. Vista panorâmica para os cafezais incluída.',
    incluso: ['Almoço completo no fogão a lenha (5 pratos + sobremesa)','Café especial da fazenda','Tour rápido pelo cafezal','Receitas para levar'],
    naoIncluso: ['Bebidas alcoólicas (disponíveis no local)','Transfer'],
    oQueLevar: ['Apetite!'],
    itinerario: [
      {hora:'12:00', atividade:'Chegada e aperitivo de boas-vindas'},
      {hora:'12:20', atividade:'Tour pelo cafezal e horta'},
      {hora:'13:00', atividade:'Almoço completo — fogão a lenha'},
      {hora:'14:30', atividade:'Sobremesa e café especial da casa'},
      {hora:'15:00', atividade:'Encerramento'}
    ],
    cancelamento: 'Cancelamento gratuito até 48h antes.',
    anfitriao: {
      nome: 'Fazenda Boa Esperança — Três Pontas',
      bio: 'Fazenda familiar com produção premiada de café especial e mesa tradicional mineira há 3 gerações.',
      foto: 'assets/images/almoco-fazenda.jpg'
    }
  },

  {
    id: 9,
    slug: 'museu-cafe-tres-pontas',
    titulo: 'Visita ao Museu do Café',
    subtitulo: 'A história de como o café transformou o Sul de Minas e o Brasil',
    categoria: 'cultural',
    municipio: 'Três Pontas',
    preco: 45,
    duracao: '2 horas',
    duracaoMin: 2,
    disponibilidade: ['Ter','Qua','Qui','Sex','Sáb','Dom'],
    horarios: ['09:00','11:00','14:00','16:00'],
    minimoPersonas: 1,
    maximoPersonas: 40,
    comGuia: true,
    transporteIncluso: false,
    transporteInfo: 'Centro histórico de Três Pontas — a pé do centro da cidade.',
    nivel: 'Fácil',
    rating: 4.5,
    totalAvaliacoes: 189,
    destaque: false,
    gratuita: false,
    imagem: 'assets/images/cafe-beans.jpg',
    galeria: ['assets/images/cafe-beans.jpg','assets/images/cupping.jpg'],
    tags: ['museu','história','café','cultural','Três Pontas'],
    descricao: 'Um dos mais completos museus sobre a cultura cafeeira do Brasil. Acervo com mais de 2.000 peças históricas, fotografias, equipamentos do século XIX e exposições interativas. O guia transforma a visita em uma viagem no tempo pela história do café em Três Pontas e no Sul de Minas.',
    incluso: ['Ingresso ao museu','Visita guiada de 2h','Café especial ao final da visita'],
    naoIncluso: ['Transporte'],
    oQueLevar: ['Câmera (proibido flash em algumas seções)'],
    itinerario: [
      {hora:'09:00', atividade:'Introdução e linha do tempo do café no Brasil'},
      {hora:'09:40', atividade:'Acervo de equipamentos históricos do século XIX'},
      {hora:'10:10', atividade:'Galeria fotográfica — colheita e cultura cafeeira'},
      {hora:'10:30', atividade:'Exposição interativa: o café de Três Pontas hoje'},
      {hora:'11:00', atividade:'Café especial e loja de souvenirs'}
    ],
    cancelamento: 'Cancelamento gratuito até 24h antes.',
    anfitriao: {
      nome: 'Museu do Café — Três Pontas',
      bio: 'Fundado em 1995. Maior acervo cafeeiro do Sul de Minas, tombado pelo patrimônio histórico municipal.',
      foto: 'assets/images/cafe-beans.jpg'
    }
  },

  {
    id: 10,
    slug: 'trilha-cafezais-tres-pontas',
    titulo: 'Trilha entre os Cafezais de Três Pontas',
    subtitulo: 'Caminhada panorâmica entre fazendas premiadas',
    categoria: 'aventura',
    municipio: 'Três Pontas',
    preco: 110,
    duracao: '4 horas',
    duracaoMin: 4,
    disponibilidade: ['Sáb','Dom'],
    horarios: ['07:00','08:00'],
    minimoPersonas: 2,
    maximoPersonas: 12,
    comGuia: true,
    transporteIncluso: false,
    transporteInfo: 'Encontro no ponto de partida da trilha, próximo ao centro.',
    nivel: 'Moderado',
    rating: 4.8,
    totalAvaliacoes: 54,
    destaque: false,
    gratuita: false,
    imagem: 'assets/images/trilha.jpg',
    galeria: ['assets/images/trilha.jpg','assets/images/cafezal-fazenda.jpg'],
    tags: ['trilha','natureza','aventura','cafezal','Três Pontas'],
    descricao: 'Trilha de 7km entre os cafezais premiados de Três Pontas com vistas para o campo e as serras ao fundo. O guia explica sobre a produção de café especial, a biodiversidade local e os segredos das fazendas. Termina no mirante com café especial servido na chegada.',
    incluso: ['Guia de trilha certificado','Café especial no mirante','Hidratação no percurso','Seguro de acidente'],
    naoIncluso: ['Transporte','Alimentação'],
    oQueLevar: ['Calçado de trilha ou esportivo','Repelente','Protetor solar','Água (mínimo 1,5L)'],
    itinerario: [
      {hora:'07:00', atividade:'Encontro, briefing de segurança e aquecimento'},
      {hora:'07:30', atividade:'Início da trilha — trecho pelos cafezais'},
      {hora:'09:00', atividade:'Parada em fazenda produtora com explicação'},
      {hora:'10:00', atividade:'Mirante: café especial e fotos panorâmicas'},
      {hora:'11:00', atividade:'Descida e encerramento'}
    ],
    cancelamento: 'Cancelamento gratuito até 48h antes. Reagendamento automático em caso de chuva forte.',
    anfitriao: {
      nome: 'Guias de Três Pontas',
      bio: 'Equipe certificada pelo Ministério do Turismo com especialização em ecoturismo e cultura cafeeira.',
      foto: 'assets/images/trilha.jpg'
    }
  },

  {
    id: 11,
    slug: 'trilha-livre-tres-pontas',
    titulo: 'Mirante do Cafezal — Trilha Autoguiada',
    subtitulo: 'Vista panorâmica gratuita sobre os cafezais de Três Pontas',
    categoria: 'gratuita',
    municipio: 'Três Pontas',
    preco: 0,
    duracao: '2 horas',
    duracaoMin: 2,
    disponibilidade: ['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
    horarios: ['Livre — durante o dia'],
    minimoPersonas: 1,
    maximoPersonas: 999,
    comGuia: false,
    transporteIncluso: false,
    transporteInfo: 'Início na Praça da Matriz — centro de Três Pontas.',
    nivel: 'Fácil',
    rating: 4.6,
    totalAvaliacoes: 267,
    destaque: false,
    gratuita: true,
    imagem: 'assets/images/mirante.jpg',
    galeria: ['assets/images/mirante.jpg'],
    tags: ['gratuita','autoguiada','mirante','trilha','Três Pontas'],
    descricao: 'Trilha autoguiada de 3,5km com sinalização completa e placas educativas sobre a produção de café especial. O mirante oferece uma vista panorâmica dos cafezais de Três Pontas — perfeita ao nascer do sol. Download do guia de áudio disponível via QR Code no ponto de partida.',
    incluso: ['Acesso gratuito','Sinalização e placas educativas','Guia digital para download'],
    naoIncluso: ['Nada — é totalmente gratuita!'],
    oQueLevar: ['Água','Protetor solar','Calçado confortável','Câmera'],
    itinerario: [
      {hora:'Livre', atividade:'Início na Praça da Matriz'},
      {hora:'+45min', atividade:'Paradas com QR codes explicativos sobre o café'},
      {hora:'+1h15', atividade:'Mirante — vista panorâmica dos cafezais'},
      {hora:'+2h', atividade:'Retorno ao centro'}
    ],
    cancelamento: 'Experiência livre — sem necessidade de reserva.',
    anfitriao: {
      nome: 'Secretaria de Turismo de Três Pontas',
      bio: 'Trilha mantida pela Prefeitura em parceria com a Rota do Café do Sul de Minas.',
      foto: 'assets/images/mirante.jpg'
    }
  },

  // ── CAMBUQUIRA ────────────────────────────────────────────

  {
    id: 12,
    slug: 'cachoeiras-cambuquira',
    titulo: 'Cachoeiras do Sul de Minas — Cambuquira',
    subtitulo: 'Trilha até as cachoeiras escondidas da Serra de Cambuquira',
    categoria: 'aventura',
    municipio: 'Cambuquira',
    preco: 90,
    duracao: '5 horas',
    duracaoMin: 5,
    disponibilidade: ['Sáb','Dom'],
    horarios: ['08:00'],
    minimoPersonas: 2,
    maximoPersonas: 15,
    comGuia: true,
    transporteIncluso: false,
    transporteInfo: 'Saída da praça principal de Cambuquira.',
    nivel: 'Moderado',
    rating: 4.9,
    totalAvaliacoes: 73,
    destaque: true,
    gratuita: false,
    imagem: 'assets/images/cachoeira.jpg',
    galeria: ['assets/images/cachoeira.jpg','assets/images/trilha.jpg'],
    tags: ['cachoeira','trilha','natureza','aventura','Cambuquira'],
    descricao: 'Uma trilha de 6km que leva até 3 cachoeiras deslumbrantes na Serra de Cambuquira, passando por mata atlântica preservada e pequenas propriedades rurais. O guia é filho de agricultores da região e conta histórias da comunidade ao longo do caminho.',
    incluso: ['Guia local certificado','Hidratação no percurso','Seguro de acidente'],
    naoIncluso: ['Alimentação'],
    oQueLevar: ['Roupa de banho','Calçado de trilha','Repelente e protetor solar'],
    itinerario: [
      {hora:'08:00', atividade:'Encontro e briefing de segurança'},
      {hora:'08:30', atividade:'Trilha de acesso — mata atlântica preservada'},
      {hora:'09:30', atividade:'1ª cachoeira — banho e descanso'},
      {hora:'10:30', atividade:'Continuação para a 2ª e 3ª cachoeiras'},
      {hora:'12:00', atividade:'Retorno pelo caminho das propriedades rurais'},
      {hora:'13:00', atividade:'Chegada e encerramento'}
    ],
    cancelamento: 'Cancelamento gratuito até 48h antes.',
    anfitriao: {
      nome: 'Ecoturismo Cambuquira',
      bio: 'Guias locais nativos de Cambuquira, parceiros da Reserva da Biosfera da Mata Atlântica.',
      foto: 'assets/images/cachoeira.jpg'
    }
  },

  {
    id: 13,
    slug: 'parque-aguas-cambuquira',
    titulo: 'Parque das Águas Minerais',
    subtitulo: 'Fontes medicinais e história na estância de Cambuquira',
    categoria: 'cultural',
    municipio: 'Cambuquira',
    preco: 40,
    duracao: '2 horas',
    duracaoMin: 2,
    disponibilidade: ['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
    horarios: ['08:00','10:00','14:00'],
    minimoPersonas: 1,
    maximoPersonas: 80,
    comGuia: false,
    transporteIncluso: false,
    transporteInfo: 'Centro de Cambuquira — o Parque fica a 5 min da praça.',
    nivel: 'Fácil',
    rating: 4.5,
    totalAvaliacoes: 321,
    destaque: false,
    gratuita: false,
    imagem: 'assets/images/parque-aguas.jpg',
    galeria: ['assets/images/parque-aguas.jpg'],
    tags: ['termal','fontes','relaxamento','bem-estar','Cambuquira'],
    descricao: 'O Parque das Águas de Cambuquira é uma das joias do Circuito das Águas Sul-Mineiro. Passeie pelos jardins históricos do século XIX, experimente as fontes minerais com diferentes propriedades terapêuticas e descanse na beleza da estância.',
    incluso: ['Ingresso ao Parque das Águas','Acesso às fontes minerais','Guia de uso das fontes'],
    naoIncluso: ['Tratamentos de spa'],
    oQueLevar: ['Copo reutilizável','Roupa confortável'],
    itinerario: [
      {hora:'08:00', atividade:'Entrada no Parque e orientação'},
      {hora:'08:20', atividade:'Percurso pelas fontes minerais'},
      {hora:'09:00', atividade:'Jardins históricos do século XIX — passeio livre'},
      {hora:'10:00', atividade:'Saída'}
    ],
    cancelamento: 'Cancelamento gratuito até 24h antes.',
    anfitriao: {
      nome: 'Parque das Águas — Cambuquira',
      bio: 'Patrimônio histórico de Cambuquira, o Parque das Águas integra o Circuito das Águas Sul-Mineiro.',
      foto: 'assets/images/parque-aguas.jpg'
    }
  },

  {
    id: 14,
    slug: 'cafe-aguas-cambuquira',
    titulo: 'Café & Águas — Experiência Integrada',
    subtitulo: 'O melhor de Cambuquira em um roteiro único',
    categoria: 'fazenda',
    municipio: 'Cambuquira',
    preco: 155,
    duracao: '4 horas',
    duracaoMin: 4,
    disponibilidade: ['Sáb','Dom'],
    horarios: ['09:00'],
    minimoPersonas: 2,
    maximoPersonas: 12,
    comGuia: true,
    transporteIncluso: false,
    transporteInfo: 'Encontro no centro de Cambuquira.',
    nivel: 'Fácil',
    rating: 4.7,
    totalAvaliacoes: 39,
    destaque: false,
    gratuita: false,
    imagem: 'assets/images/spa-aguas-cafe.jpg',
    galeria: ['assets/images/spa-aguas-cafe.jpg','assets/images/cupping.jpg'],
    tags: ['café','águas','integrado','Cambuquira'],
    descricao: 'A experiência que une os dois grandes tesouros de Cambuquira: o café especial e as águas minerais. Você começa com um cupping de cafés locais, visita uma pequena propriedade produtora de café, e termina com uma sessão relaxante no Parque das Águas.',
    incluso: ['Cupping de cafés de Cambuquira e região','Visita guiada a propriedade produtora','Ingresso ao Parque das Águas','Café especial para levar (100g)'],
    naoIncluso: ['Transporte','Refeições'],
    oQueLevar: ['Roupa confortável','Copo reutilizável'],
    itinerario: [
      {hora:'09:00', atividade:'Cupping de abertura — cafés do Sul de Minas'},
      {hora:'10:00', atividade:'Visita a propriedade produtora de café'},
      {hora:'11:00', atividade:'Degustação de frutos e processo de pós-colheita'},
      {hora:'12:00', atividade:'Parque das Águas — fontes minerais e relaxamento'},
      {hora:'13:00', atividade:'Encerramento'}
    ],
    cancelamento: 'Cancelamento gratuito até 48h antes.',
    anfitriao: {
      nome: 'Rota do Café — Cambuquira',
      bio: 'Parceria entre produtores de café e o Parque das Águas para oferecer uma experiência única em Cambuquira.',
      foto: 'assets/images/spa-aguas-cafe.jpg'
    }
  },

  {
    id: 15,
    slug: 'almoco-roça-cambuquira',
    titulo: 'Almoço na Roça — Sabores do Campo',
    subtitulo: 'Mesa farta e autêntica em sítio familiar de Cambuquira',
    categoria: 'gastronomia',
    municipio: 'Cambuquira',
    preco: 110,
    duracao: '3 horas',
    duracaoMin: 3,
    disponibilidade: ['Sáb','Dom'],
    horarios: ['12:00'],
    minimoPersonas: 4,
    maximoPersonas: 20,
    comGuia: false,
    transporteIncluso: false,
    transporteInfo: 'Sítio a 6km do centro de Cambuquira. Transfer disponível por +R$ 25/pax.',
    nivel: 'Fácil',
    rating: 4.8,
    totalAvaliacoes: 96,
    destaque: false,
    gratuita: false,
    imagem: 'assets/images/queijo.jpg',
    galeria: ['assets/images/queijo.jpg'],
    tags: ['gastronomia','almoço','sítio','culinária mineira','Cambuquira'],
    descricao: 'Um almoço caipira de verdade: tudo preparado no fogão a lenha, com ingredientes do próprio sítio. Frango caipira, angu, couve, feijão preto, queijo minas fresco e doces artesanais. A dona da casa recebe os visitantes como família.',
    incluso: ['Almoço completo (4 pratos + sobremesa)','Café especial da casa','Visita ao quintal e horta'],
    naoIncluso: ['Transfer','Bebidas alcoólicas'],
    oQueLevar: ['Apetite e disposição para conversar com os moradores'],
    itinerario: [
      {hora:'12:00', atividade:'Chegada e tour pelo quintal'},
      {hora:'12:30', atividade:'Mesa posta — almoço caipira'},
      {hora:'14:00', atividade:'Sobremesa e café da casa'},
      {hora:'15:00', atividade:'Encerramento'}
    ],
    cancelamento: 'Cancelamento gratuito até 48h antes.',
    anfitriao: {
      nome: 'Sítio Dona Lurdes — Cambuquira',
      bio: 'Dona Lurdes e sua família recebem visitantes há 10 anos no sítio. Culinária 100% artesanal, sem industrializados.',
      foto: 'assets/images/queijo.jpg'
    }
  },

  {
    id: 16,
    slug: 'centro-historico-cambuquira',
    titulo: 'Centro Histórico Autoguiado — Cambuquira',
    subtitulo: 'Descubra a arquitetura e história da estância a pé',
    categoria: 'gratuita',
    municipio: 'Cambuquira',
    preco: 0,
    duracao: '1h30',
    duracaoMin: 1.5,
    disponibilidade: ['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'],
    horarios: ['Livre'],
    minimoPersonas: 1,
    maximoPersonas: 999,
    comGuia: false,
    transporteIncluso: false,
    transporteInfo: 'Início na praça central de Cambuquira.',
    nivel: 'Fácil',
    rating: 4.4,
    totalAvaliacoes: 198,
    destaque: false,
    gratuita: true,
    imagem: 'assets/images/centro-historico.jpg',
    galeria: ['assets/images/centro-historico.jpg'],
    tags: ['gratuita','autoguiada','centro histórico','Cambuquira'],
    descricao: 'Roteiro autoguiado pela arquitetura eclética do centro histórico de Cambuquira, passando pela Praça Dr. Pio X, a Igreja Matriz, o Chafariz histórico, o Coreto e as casarões do início do século XX que fazem da cidade um cartão-postal.',
    incluso: ['Roteiro gratuito para download','Guia de áudio via QR Code'],
    naoIncluso: ['Ingresso ao Parque das Águas'],
    oQueLevar: ['Fones de ouvido','Calçado confortável','Câmera'],
    itinerario: [
      {hora:'Livre', atividade:'Praça Dr. Pio X — ponto de partida'},
      {hora:'+20min', atividade:'Igreja Matriz e Chafariz histórico'},
      {hora:'+45min', atividade:'Casarões do século XX'},
      {hora:'+90min', atividade:'Retorno pela orla do Parque das Águas'}
    ],
    cancelamento: 'Experiência livre — sem necessidade de reserva.',
    anfitriao: {
      nome: 'Secretaria de Turismo de Cambuquira',
      bio: 'Roteiro desenvolvido pelo município em parceria com o Instituto do Patrimônio Histórico de Minas Gerais.',
      foto: 'assets/images/centro-historico.jpg'
    }
  }
];

const ROTEIROS = [
  {
    id: 1,
    slug: 'fim-de-semana-varginha',
    titulo: 'Fim de Semana em Varginha',
    subtitulo: 'Dois dias na Capital Mundial do Café',
    duracao: '2 dias / 1 noite',
    municipios: ['Varginha'],
    preco: 380,
    nivel: 'Fácil',
    destaque: true,
    imagem: 'assets/images/varginha-cidade.jpg',
    descricao: 'Mergulhe no universo cafeeiro de Varginha: cupping com barista campeão, rota pelos mercados e um jantar harmonizado para encerrar com chave de ouro.',
    experiencias: [1, 3, 2]
  },
  {
    id: 2,
    slug: 'imersao-tres-pontas',
    titulo: 'Imersão do Café em Três Pontas',
    subtitulo: 'Do cafezal à xícara em um sábado inesquecível',
    duracao: '1 dia (sábado)',
    municipios: ['Três Pontas'],
    preco: 300,
    nivel: 'Moderado',
    destaque: true,
    imagem: 'assets/images/imersao-tres-pontas.jpg',
    descricao: 'Conheça toda a cadeia produtiva do café premiado de Três Pontas: fazenda, torra e degustação em um único dia.',
    experiencias: [6, 8, 9]
  },
  {
    id: 3,
    slug: 'aguas-cafezais-cambuquira',
    titulo: 'Águas & Cafezais — Cambuquira',
    subtitulo: 'Relaxamento e natureza em um fim de semana único',
    duracao: '2 dias / 1 noite',
    municipios: ['Cambuquira'],
    preco: 310,
    nivel: 'Fácil',
    destaque: false,
    imagem: 'assets/images/aguas-cafezais.jpg',
    descricao: 'Cachoeiras, fontes minerais e café especial — o melhor de Cambuquira em dois dias de pura desconexão.',
    experiencias: [12, 14, 15, 13]
  },
  {
    id: 4,
    slug: 'rota-completa-3-municipios',
    titulo: 'Rota Completa — 3 Municípios',
    subtitulo: 'Varginha, Três Pontas e Cambuquira em uma grande aventura',
    duracao: '3 dias / 2 noites',
    municipios: ['Varginha', 'Três Pontas', 'Cambuquira'],
    preco: 780,
    nivel: 'Moderado',
    destaque: true,
    imagem: 'assets/images/hero.jpg',
    descricao: 'A experiência definitiva da Rota do Café do Sul de Minas: cupping em Varginha, imersão em fazenda de Três Pontas e cachoeiras de Cambuquira.',
    experiencias: [1, 6, 10, 12, 15]
  },
  {
    id: 5,
    slug: 'premium-cafe-sul-minas',
    titulo: 'Premium: Café & Gastronomia',
    subtitulo: 'A melhor seleção gastronômica e cafeeira da rota',
    duracao: '3 dias / 2 noites',
    municipios: ['Varginha', 'Três Pontas'],
    preco: 680,
    nivel: 'Fácil',
    destaque: false,
    imagem: 'assets/images/premium-gastronomia.jpg',
    descricao: 'Para os amantes de gastronomia e café: torra assistida, cupping, almoço na fazenda e jantar harmonizado — o melhor dos sabores do Sul de Minas.',
    experiencias: [5, 1, 8, 2, 7]
  }
];

const MUNICIPIOS = [
  {
    nome: 'Varginha',
    subtitulo: 'Capital Mundial do Café',
    descricao: 'Referência mundial na produção e comércio de cafés especiais.',
    cor: '#6B3A2A',
    totalExperiencias: 5,
    destaques: ['Cupping com baristas campeões','Torrefações históricas','Rota de cafeterias']
  },
  {
    nome: 'Três Pontas',
    subtitulo: 'Terra do Café Premiado',
    descricao: 'Município com algumas das fazendas de café mais premiadas do país.',
    cor: '#4A7C2F',
    totalExperiencias: 6,
    destaques: ['Fazendas centenárias','Museu do Café','Trilhas entre cafezais']
  },
  {
    nome: 'Cambuquira',
    subtitulo: 'Águas & Natureza',
    descricao: 'Estância hidromineral com cachoeiras, fontes e café especial.',
    cor: '#2D5016',
    totalExperiencias: 5,
    destaques: ['Cachoeiras da Serra','Parque das Águas Minerais','Gastronomia do campo']
  }
];

const CATEGORIAS = [
  { id: 'fazenda', label: 'Fazendas de Café', icon: '☕', cor: '#6B3A2A' },
  { id: 'gastronomia', label: 'Gastronomia', icon: '🍽️', cor: '#C8963E' },
  { id: 'aventura', label: 'Aventura & Natureza', icon: '🏔️', cor: '#4A7C2F' },
  { id: 'cultural', label: 'Cultural & Histórico', icon: '🎨', cor: '#8B5E3C' },
  { id: 'gratuita', label: 'Experiências Gratuitas', icon: '✨', cor: '#2D5016' }
];
